MercuryTechnologies/ghc-specter

flake.lock, flake.nix
flake.nix is introduced for providing dev shell for this project.
Nix flake is deliberately chosen for easing a later composition into a bigger project.
=> Provide devShell using nix flake

app/Main.hs, flake.nix, fourmolu.yaml, src/Lib.hs
=> Use fourmolu

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Render.hs
Using Bulma CSS package, the web display is organized in a more user/dev-friendly form.
=> UI Layout using Bulma CSS

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Render.hs, app/toolbox-server/Toolbox/Server/Types.hs, examples/timing/A.hs, examples/timing/B.hs, flake.nix, package.yaml, src/Plugin/Timing.hs, src/Toolbox/Channel.hs, src/Toolbox/Comm.hs
By using driverPlugin and runPhaseHook, we are able to timestamp GHC timing per each module compilation as we want. As the simplest, I measure each module compilation start and end timing as well as the start time of the overarching GHC session (using global variable trick).
=> Timing plugin

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Render.hs, app/toolbox-server/Toolbox/Render/Timing.hs, app/toolbox-server/Toolbox/Server/Types.hs, package.yaml, src/Toolbox/Channel.hs
The module compilation timing is visualized as online SVG image.
=> Module compilation timing visualization

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Server/Types.hs
Messages from GHC are too frequent, so limit update interval.
=> Update UI with time interval

package.yaml, src/Plugin/Timing.hs
previous IORef prototype suffers from race condition, so used STM and atomic operation. 
also made sure strictness.
=> Safe sessionRef update once and only once

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Render/ModuleGraph.hs, package.yaml, src/Plugin/Timing.hs, src/Toolbox/Channel.hs, src/Toolbox/Util/Graph.hs, test/Toolbox/Util/GraphSpec.hs
From inefficient [(Int, [Int])] to IntMap [Int]
=> Use IntMap for dep graph information

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Render/ModuleGraph.hs, app/toolbox-server/Toolbox/Util/OGDF.hs, package.yaml
Introduce GraphLayouter monad which is a simple ResourceT wrapper, so that C++ resource allocation can be done safely.
=> Resource-safe GraphLayouter Monad

app/toolbox-server/Toolbox/Render.hs, app/toolbox-server/Toolbox/Render/ModuleGraph.hs, app/toolbox-server/Toolbox/Server/Types.hs, src/Plugin/Timing.hs
Submodule graph panel handles hover event separately to show local depedency.
=> Submodule graph event handling

app/toolbox-server/Toolbox/Render.hs, app/toolbox-server/Toolbox/Render/ModuleGraph.hs, app/toolbox-server/Toolbox/Server/Types.hs, app/toolbox-server/Toolbox/Worker.hs, package.yaml
User can choose the detail level (up to 30 items, 100 items and 300 items) for convenience.
=> Show subgraphs in different detail levels

app/toolbox-server/Main.hs, app/toolbox-server/Toolbox/Render.hs, app/toolbox-server/Toolbox/Render/ModuleGraph.hs, app/toolbox-server/Toolbox/Render/Session.hs, app/toolbox-server/Toolbox/Render/SourceView.hs, app/toolbox-server/Toolbox/Render/Timing.hs, app/toolbox-server/Toolbox/Server/Types.hs, app/toolbox-server/Toolbox/Worker/Hie.hs
Using the information in the hie file, SourceView panel per module is introduced.  Each top-level declaration is marked with an arrow and shown on the right panel.
=> Show source code with marking top-level declaration using hie 

daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/Timing.hs, daemon/src/GHCSpecter/Server/Types.hs
For user's convenience, I introduced check box UI for choosing the graph is dynamically aligned. 
User can also choose whether bar graph is partitioned by phase or not.
=> Timing bar graph is optionally aligned to the bottom-right corner

daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/Timing.hs, daemon/src/GHCSpecter/Server/Types.hs, daemon/src/GHCSpecter/Util/Timing.hs
Timing bar graph has colored background, especially red-colored alert for choked region.
=> CPU Usage shown with color code in timing bar graph

daemon/app/Main.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Render/Timing.hs, daemon/src/GHCSpecter/Server/Types.hs, daemon/src/GHCSpecter/UI/Types.hs, daemon/src/GHCSpecter/UI/Types/Event.hs, daemon/src/GHCSpecter/Worker/ModuleGraph.hs
Server state and UI state/event are separated.
=> Separate out UI.Types and UI.Types.Event from Server.Types

daemon/app/Main.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Server/Types.hs, daemon/src/GHCSpecter/UI/Types.hs, plugin/src/GHCSpecter/Channel.hs, plugin/src/Plugin/GHCSpecter.hs
Now using bidirectional socket, daemon can send a signal for pausing the GHC.
=> Pause / Resume GHC session via daemon

daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/Timing.hs, daemon/src/GHCSpecter/UI/Types.hs
The branching logic resides in Control monad.
=> Tab selection as modal control logic

daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render/Timing.hs, daemon/src/GHCSpecter/UI/Types.hs
=> Turn on mouse move event handling only while dragging

daemon/app/Main.hs, daemon/src/GHCSpecter/Render/Components/TextView.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Worker/ModuleGraph.hs
Here, I introduce a new TextView component which shows monospaced text with highlighting annotation.
This will be extended to support graph annotation. 
I also moved layOutGraph to Worker.ModuleGraph module.
=> TextView SVG component for showing text with annotation

daemon/app/Main.hs, daemon/src/GHCSpecter/GraphLayout/Sugiyama.hs, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Server/Types.hs, daemon/src/GHCSpecter/Worker/CallGraph.hs, daemon/src/GHCSpecter/Worker/Hie.hs, daemon/src/GHCSpecter/Worker/ModuleGraph.hs
As Hie information arrived, call graph visualization info is computed and then rendered.
=> Render call graph

daemon/app/Main.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Control/Runner.hs, daemon/src/GHCSpecter/Control/Types.hs, daemon/src/GHCSpecter/Driver.hs, plugin/src/Plugin/GHCSpecter.hs
the starting point of mainLoop was wrong (It was ignoring all other events than Tab until the first Tab event comes)
I also separated out get/put primitives of UI and SS.
=> Bug fix at the start

plugin/src/Plugin/GHCSpecter.hs
As driverPlugin can dynamically modify the content of plugins as a part of HscEnv, typecheckPlugin is unified into the driver plugin. With this mechanism, we can share variables across multiple plugins.
=> Unify plugin via driverPlugin

daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs
Show console always when paused.
=> UI layout change with console

daemon/assets/ghc-specter.css, daemon/package.yaml, daemon/src/GHCSpecter/Data/Assets.hs, daemon/src/GHCSpecter/Driver.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/Components/Console.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Util/SourceTree.hs, flake.nix
No more bulma. Instead, the web frontend is more stylish with dev-oriented smaller fonts. I also separate out CSS attributes as a separate css asset file.
=> Return to plain custom CSS 

daemon/assets/ghc-specter.css, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/Components/Console.hs, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Render/Timing.hs, daemon/src/GHCSpecter/UI/Constants.hs
especially, fonts used in SVG are now fixed so to guarantee the same layout across platforms and browsers.
=> Further style adjustment

daemon/src/GHCSpecter/Render/ModuleGraph.hs, daemon/src/GHCSpecter/Util/ModuleGraph.hs
horizontal scrolling for each modgraph panel.
also moved irrelevant print functions to Util.ModuleGraph.
=> Scroll adjustment for modgraph

daemon/src/GHCSpecter/Control.hs, plugin/package.yaml, plugin/src/GHCSpecter/Channel/Inbound/Types.hs, plugin/src/Plugin/GHCSpecter.hs, plugin/src/Plugin/GHCSpecter/Comm.hs, plugin/src/Plugin/GHCSpecter/Console.hs, plugin/src/Plugin/GHCSpecter/Task/Core2Core.hs
Now introduce `:list-core` command, and `:print-core` accepts arguments for specific variables to print!
=> list-core command and print-core per var

cabal.project, daemon/src/GHCSpecter/Driver/Comm.hs, daemon/src/GHCSpecter/Worker/Hie.hs, flake.lock, flake.nix, plugin/package.yaml, plugin/src/GHCSpecter/Channel/Outbound/Types.hs, plugin/src/Plugin/GHCSpecter.hs, plugin/src/Plugin/GHCSpecter/Hooks.hs, plugin/src/Plugin/GHCSpecter/Tasks.hs, plugin/src/Plugin/GHCSpecter/Util.hs
ghc-specter now supports both GHC 9.2 and GHC 9.4!
=> Build on GHC 9.4

daemon/assets/ghc-specter.css, daemon/src/GHCSpecter/Render/Session.hs, plugin/src/GHCSpecter/Channel/Outbound/Types.hs, plugin/src/Plugin/GHCSpecter.hs
It is useful to fully show how GHC was called. Also did a little work on styling.
=> Show GHC path, current directory and CLI arguments 

daemon/src/GHCSpecter/Data/Timing/Types.hs, daemon/src/GHCSpecter/Data/Timing/Util.hs, daemon/src/GHCSpecter/Render/Timing.hs
and rename TimingInfo to PipelineInfo (as it will be used for memory information).
=> Use DriverId in TimingTable

plugin/src/Plugin/GHCSpecter.hs
Previously, ghci + ghc-specter did not work properly as module graph sent to the daemon was empty. 
ghci rerun driver plugin on every reload, and the first module graph was also computed at the second driver run (i.e. the first driver run does not have any module information), so on every driver plugin call, we compare module graph info stored in the session variable and update it if different.
=> Update module graph information correctly in ghci session

logcat/app/logcat/Main.hs, logcat/app/logcat/Render.hs, logcat/ghc-specter-logcat.cabal, nix/ghcHEAD/ghcHEAD-cabal.project
Blurry rendering is cured on macos.
before:
after:
=> HiDPI rendering

logcat/app/logcat/Control.hs, logcat/app/logcat/Log.hs, logcat/app/logcat/Main.hs, logcat/app/logcat/Render.hs, logcat/app/logcat/Types.hs, nix/ghcHEAD/ghcHEAD-cabal.project, nix/ghcHEAD/shell.nix
process hovering events on each log types and show the highlighted logs in the timeline panel. Also shows total number of raw eventlog bytes for the sake of monitoring.
=> Responsive logcat interface with highlighted log types and stats

logcat/app/logcat/Log.hs, logcat/app/logcat/Render.hs, logcat/app/logcat/Render/Heap.hs, logcat/app/logcat/Render/Timeline.hs, logcat/app/logcat/Render/Util.hs, logcat/app/logcat/Types.hs, logcat/ghc-specter-logcat.cabal
=> Show live heap view graphically

daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Control/Runner.hs, daemon/src/GHCSpecter/Control/Types.hs, daemon/src/GHCSpecter/Driver.hs, daemon/src/GHCSpecter/Driver/Session.hs, daemon/src/GHCSpecter/Driver/Session/Types.hs, daemon/src/GHCSpecter/Worker/Timing.hs
replaced get/put with modify. 
I also use TQueue instead of TChan for event demux and prioritize background event than UI events.
=> Timing state update bug fix due to non-transactional update

daemon-exp/app/ghc-specter-daemon-exp/Handler.hs, daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/ModuleGraph.hs, daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs, daemon-exp/app/ghc-specter-daemon-exp/Timing.hs, daemon-exp/app/ghc-specter-daemon-exp/Types.hs, daemon-exp/app/ghc-specter-daemon-exp/Util.hs, daemon-exp/ghc-specter-daemon-exp.cabal, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/UI/Types/Event.hs, render/src/GHCSpecter/Graphics/DSL.hs
also refactor out Handler and Renderer modules
now Control coroutine process is branching according to the mode.
=> Handling mouse-over events on module graph items

daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Timing.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Driver.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/UI/Types.hs
I get rid of split uses of get/put UI and server state. Use only modify* for updating state.
=> Transactional state update

daemon-exp/app/ghc-specter-daemon-exp/Config.hs, daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/ModuleGraph.hs, daemon-exp/ghc-specter-daemon-exp.cabal, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Util/Transformation.hs
it is revived in the native app.
=> Submodule graph rendering

daemon/src/GHCSpecter/Control.hs
The UI state was not updated properly. Now uses transactional update.
=> Bug fix in console command processing

daemon-exp/app/ghc-specter-daemon-exp/Config.hs, daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Common.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/ModuleGraph.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Session.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/SourceView.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Timing.hs, daemon-exp/ghc-specter-daemon-exp.cabal, daemon/ghc-specter-daemon.cabal, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render/Components/Tab.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Render/Tab.hs, daemon/src/GHCSpecter/UI/Types.hs
=> Supplementary view for each module

daemon-exp/app/ghc-specter-daemon-exp/Config.hs, daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Common.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Session.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/Components/TextView.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/UI/Constants.hs, daemon/src/GHCSpecter/UI/Types.hs
=> Module status in session view

daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Common.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/ModuleGraph.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Session.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/SourceView.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Timing.hs, daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs, daemon-exp/app/ghc-specter-daemon-exp/Types.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Control/Runner.hs, daemon/src/GHCSpecter/Control/Types.hs, daemon/src/GHCSpecter/Driver.hs, daemon/src/GHCSpecter/Driver/Session.hs, daemon/src/GHCSpecter/Render.hs, daemon/src/GHCSpecter/UI/Types.hs
and EventMap is now reorganized into view backend  as generated from Scene, which also shared the same type index.
=> Type-indexed view backend / runner / control  

daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Common.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/ModuleGraph.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Session.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/SourceView.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Timing.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Control/Runner.hs, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/Components/ModuleTree.hs, daemon/src/GHCSpecter/Render/Components/Tab.hs, daemon/src/GHCSpecter/Render/Components/TextView.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/Render/ConcurReplicaSVG.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/UI/Types/Event.hs, render/src/GHCSpecter/Graphics/DSL.hs
Now ad hoc text-based event handling is replaced by Event type.
=> Type-safe event handling

daemon/app/GHCSpecter/ConcurReplica/DOM.hs, daemon/app/GHCSpecter/ConcurReplica/DOM/Events.hs, daemon/app/GHCSpecter/ConcurReplica/Run.hs, daemon/app/GHCSpecter/ConcurReplica/SVG.hs, daemon/app/GHCSpecter/ConcurReplica/Types.hs, daemon/app/GHCSpecter/ConcurReplica/WaiHandler.hs, daemon/app/GHCSpecter/Driver/Web.hs, daemon/app/GHCSpecter/Render/Web.hs, daemon/app/GHCSpecter/Render/Web/ConcurReplicaSVG.hs, daemon/app/GHCSpecter/Render/Web/Console.hs, daemon/app/GHCSpecter/Render/Web/ConsoleItem.hs, daemon/app/GHCSpecter/Render/Web/GHCCore.hs, daemon/app/GHCSpecter/Render/Web/ModuleGraph.hs, daemon/app/GHCSpecter/Render/Web/Session.hs, daemon/app/GHCSpecter/Render/Web/SourceView.hs, daemon/app/GHCSpecter/Render/Web/Timing.hs, daemon/app/GHCSpecter/Render/Web/Util.hs, daemon/app/Main.hs, daemon/ghc-specter-daemon.cabal, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/Components/TextView.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs
and now ghc-specter-daemon library is free of web-specific stuff.
=> Separate out web-related part

daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs, daemon/app/GHCSpecter/Render/Web/ConcurReplicaSVG.hs, daemon/src/GHCSpecter/Render/Components/Console.hs, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/Components/ModuleTree.hs, daemon/src/GHCSpecter/Render/Components/Tab.hs, daemon/src/GHCSpecter/Render/Components/TextView.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/Render/Components/Util.hs, daemon/src/GHCSpecter/Render/Session.hs, render/src/GHCSpecter/Graphics/DSL.hs
Separate out general part from shape-specific part. towards bounding box filtering
=> Refactor out Shape. and Primitive has general BoundingBox and HitEvent

daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs, daemon/src/GHCSpecter/Render/Components/Console.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Util/Transformation.hs, plugin/src/Plugin/GHCSpecter/Tasks/Core2Core.hs, render/src/GHCSpecter/Graphics/DSL.hs
The result is displayed in console and also in the corresponding supplementary view of the source.
=> Show GHC Core upon console request 

daemon/src/GHCSpecter/Render/Components/Console.hs, daemon/src/GHCSpecter/Render/Components/ModuleTree.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/Render/Components/Util.hs, render/src/GHCSpecter/Graphics/DSL.hs
The spurious Nothing case is eliminated.
=> Use NonEmpty and safe ViewPort sum

daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Parts/Console.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Parts/ModuleGraph.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Parts/Session.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Parts/SourceView.hs, daemon-exp/app/ghc-specter-daemon-exp/Render/Parts/Timing.hs, daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs, daemon/src-ghc96/GHCSpecter/Worker/Hie.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Render/Components/Console.hs, daemon/src/GHCSpecter/Render/Components/GraphView.hs, daemon/src/GHCSpecter/Render/Components/ModuleTree.hs, daemon/src/GHCSpecter/Render/Components/Tab.hs, daemon/src/GHCSpecter/Render/Components/TextView.hs, daemon/src/GHCSpecter/Render/Components/TimingView.hs, daemon/src/GHCSpecter/Render/Session.hs, daemon/src/GHCSpecter/Render/SourceView.hs, daemon/src/GHCSpecter/Util/Transformation.hs, render/src/GHCSpecter/Graphics/DSL.hs
Now Scene is used for both rendering and eventmap. and it has extent information. 
Scroll handler is limited by the content extent.
=> Unify Scene and EventMap and limit scroll by content extent

daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/Console.hs, daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/Main.hs, daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/ModuleGraph.hs, daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/Session.hs, daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/SourceView.hs, daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/Timing.hs, daemon-exp/app/ghc-specter-daemon-exp/GHCSpecter/Gtk/Types.hs, daemon-exp/app/ghc-specter-daemon-exp/Main.hs, daemon/app/ghc-specter-daemon/GHCSpecter/Driver/Web.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Control/Runner.hs, daemon/src/GHCSpecter/Control/Types.hs, daemon/src/GHCSpecter/UI/Constants.hs, daemon/src/GHCSpecter/Util/Transformation.hs, render/src/GHCSpecter/Graphics/DSL.hs
towards frame-based rendering regularization. A stage, which is a set of scenes, is constructed before frame rendering.
=> Intermediate Stage data for frame

.gitignore, docs/how-it-works.rst
=> Fixes couple of typo in the how-it-works doc

daemon/ghc-specter-daemon.cabal, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Driver/Terminal.hs, daemon/src/GHCSpecter/Layouter/Text.hs, daemon/src/GHCSpecter/UI/Types.hs, daemon/src/GHCSpecter/UI/Types/Event.hs, daemon/src/GHCSpecter/Util/Dump.hs, daemon/src/GHCSpecter/Util/Print.hs, plugin/src-ghc96/Plugin/GHCSpecter.hs, plugin/src-ghc96/Plugin/GHCSpecter/Init.hs, plugin/src/GHCSpecter/Config.hs
The full timing information collected until the current point can be dumped into a SVG file by console command.
=> add dump-timing feature 

daemon/app/ghc-specter-daemon/ImGuiMain.hs, daemon/app/ghc-specter-daemon/Util/Color.hs, daemon/app/ghc-specter-daemon/Util/GUI.hs, daemon/app/ghc-specter-daemon/Util/Orphans.hs, daemon/app/ghc-specter-daemon/Util/Plot.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, daemon/ghc-specter-daemon.cabal
also refactored modules and functions to tidy up the UI code.
=> show timing view and memory view on imgui

daemon/app/ghc-specter-daemon/ImGuiMain.hs, daemon/app/ghc-specter-daemon/Main.hs, daemon/app/ghc-specter-daemon/Util/Color.hs, daemon/app/ghc-specter-daemon/Util/GUI.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, daemon/src/GHCSpecter/Control.hs, flake.lock
mouse move events (hover events) in module graph are properly handled.
=> Event handling in imgui backend

daemon/app/ghc-specter-daemon/Handler.hs, daemon/app/ghc-specter-daemon/ImGuiMain.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, daemon/ghc-specter-daemon.cabal, flake.lock
mouse click events are handled now.
=> Submodule cluster graph is revived when clicked

flake.nix
can be invoked by `nix develop .#env`
=> env shell (ghc-specter-* preinstalled)

daemon/app/ghc-specter-daemon/Main.hs, daemon/app/ghc-specter-daemon/Render.hs, daemon/app/ghc-specter-daemon/Render/Common.hs, daemon/app/ghc-specter-daemon/Render/ModuleGraph.hs, daemon/app/ghc-specter-daemon/Render/Session.hs, daemon/app/ghc-specter-daemon/Render/TimingView.hs, daemon/app/ghc-specter-daemon/Util/GUI.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, daemon/ghc-specter-daemon.cabal, daemon/src/GHCSpecter/Control.hs
with a few refactoring: makeTabContents and renderComponent
=> session panel migrated to imgui

daemon/app/ghc-specter-daemon/Render.hs, daemon/app/ghc-specter-daemon/Render/Console.hs, daemon/app/ghc-specter-daemon/Render/Session.hs, daemon/app/ghc-specter-daemon/Render/SourceView.hs, daemon/app/ghc-specter-daemon/Util/GUI.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, daemon/csrc/shim.cpp, daemon/ghc-specter-daemon.cabal, daemon/src/GHCSpecter/UI/Types.hs, flake.lock, plugin/src/GHCSpecter/Config.hs
Now all the major functions are restored. success in porting!
=> Console is back

daemon/app/ghc-specter-daemon/Handler.hs, daemon/app/ghc-specter-daemon/Main.hs, daemon/app/ghc-specter-daemon/Render.hs, daemon/app/ghc-specter-daemon/Render/Common.hs, daemon/app/ghc-specter-daemon/Render/TimingView.hs, daemon/app/ghc-specter-daemon/Util/GUI.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/UI/Types.hs, daemon/src/GHCSpecter/UI/Types/Event.hs
Zooming is now supported by Ctrl + scroll  on timing view.
=> Zoom in/out in timing view

daemon/app/ghc-specter-daemon/Render.hs, daemon/app/ghc-specter-daemon/Render/TimingView.hs, daemon/app/ghc-specter-daemon/Util/GUI.hs, flake.lock
=> Use status bar for some messages

plugin/src-ghc96/Plugin/GHCSpecter/Hooks.hs
hs-boot does not proceed with assembler phase onward. therefore, need to mark end at the end of HscBackend.
=> Address hs-boot timing handling problem.

daemon/app/ghc-specter-daemon/Render/ModuleGraph.hs, daemon/app/ghc-specter-daemon/Render/TimingView.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/UI/Types/Event.hs, flake.lock
Revived freeze/thaw timing graph, partition phases, blocker detail levels
=> Revive miscellaneous options

plugin/ghc-specter-plugin.cabal, plugin/src/Plugin/GHCSpecter/Console.hs
it just works without modification.
=> Revive ghc-debug support!

plugin/ghc-specter-plugin.cabal, plugin/src-ghc96/Plugin/GHCSpecter.hs, plugin/src-ghc96/Plugin/GHCSpecter/Hooks.hs
previously, it was notified inside typecheck plugin, which is before HIE file creation. Now done immediately after HscPostTc phase.
=> HIE file generation is notified at a correct place

daemon/src/GHCSpecter/Server/Types.hs, daemon/src/GHCSpecter/UI/Components/ModuleTree.hs, daemon/src/GHCSpecter/Util/SourceTree.hs, daemon/src/GHCSpecter/Worker/ModuleGraph.hs, plugin/src-ghc96/Plugin/GHCSpecter.hs
intermediate module prefix node in module tree should not have a bogus breakpoint.
=> Bug fix in breakpoint box at non-module item in module tree

daemon/src-ghc96/GHCSpecter/Worker/Hie.hs, daemon/src/GHCSpecter/Control.hs, daemon/src/GHCSpecter/Control/Runner.hs, daemon/src/GHCSpecter/Data/Timing/Util.hs, daemon/src/GHCSpecter/Driver/Comm.hs, daemon/src/GHCSpecter/Driver/Session.hs, daemon/src/GHCSpecter/Server/Types.hs, daemon/src/GHCSpecter/UI/Components/GraphView.hs, daemon/src/GHCSpecter/UI/Components/ModuleTree.hs, daemon/src/GHCSpecter/UI/Components/TimingView.hs, daemon/src/GHCSpecter/UI/Console.hs, daemon/src/GHCSpecter/UI/Constants.hs, daemon/src/GHCSpecter/UI/Session.hs, daemon/src/GHCSpecter/UI/SourceView.hs, daemon/src/GHCSpecter/UI/Tab.hs, daemon/src/GHCSpecter/Util/SourceTree.hs, daemon/src/GHCSpecter/Worker/CallGraph.hs, daemon/src/GHCSpecter/Worker/ModuleGraph.hs, daemon/src/GHCSpecter/Worker/Timing.hs
removed most of (^.), (.~) and (%~). 
Remaining parameterized lenses will be removed in the following PR so that we will have no more lens deps and reduce the dep footprint.
=> Remove most of lens use

daemon/app/ghc-specter-daemon/Util/GUI.hs, flake.lock
and exit when an error happens, no segfault.
=> Capture GLFW error code and messages

daemon/app/ghc-specter-daemon/Render.hs, daemon/app/ghc-specter-daemon/Util/Render.hs, flake.lock
for more efficient use of display
=> menubar, modal dialogs and division panel
