MercuryTechnologies/ghc-specter

flake.lock
flake.nix

For rendering inspection results interactively, I am considering IPC communication between GHC and a HTML serving daemon. To minimize UI dev efforts for prototype, server-side rendering framework concur-replica is being evaluated, and this PR fixes some build issues.

Fix concur-replica build 

---

examples/A.hs
package.yaml
src/Plugin/CheckImports.hs

Plugin.CheckImports checks unqualified imports in the module which the plugin runs against.
This plugin works only with GHC 9.2.

CheckImports plugin

---

app/toolbox-server.hs
package.yaml
src/Plugin/CheckImports.hs

No more hard-coded socket file path. Socket file used for comm channel will be explicitly passed via -fplugin-opt

socket file plugin argument

---

app/toolbox-server/Main.hs
app/toolbox-server/Toolbox/Render.hs
app/toolbox-server/Toolbox/Render/ModuleGraph.hs
app/toolbox-server/Toolbox/Render/Session.hs
app/toolbox-server/Toolbox/Server/Types.hs
examples/timing/C.hs
flake.nix
package.yaml
src/Plugin/Timing.hs
src/Toolbox/Channel.hs

ModuleGraph data structure is extracted from GHC session and converted to a simplified graph data structure, which is sent to display daemon.

Extract module dependency graph from GHC session

---

app/toolbox-server/Main.hs
app/toolbox-server/Toolbox/Render/ModuleGraph.hs
app/toolbox-server/Toolbox/Render/Session.hs
app/toolbox-server/Toolbox/Render/Timing.hs
app/toolbox-server/Toolbox/Server/Types.hs
app/toolbox-server/Toolbox/Util/OGDF.hs
app/toolbox-server/Toolbox/Worker.hs
src/Plugin/Timing.hs
src/Toolbox/Util/Graph.hs

With the generated module graph layout, dynamic concur-replica SVG components are generated. 
I also added a simple progress bar below the module label to display the current build status in terms of # of compiled modules inside the cluster.

Dynamic module graph generation and progress bar

---

app/toolbox-server/Main.hs
app/toolbox-server/Toolbox/Render.hs
app/toolbox-server/Toolbox/Render/ModuleGraph.hs
app/toolbox-server/Toolbox/Server/Types.hs
app/toolbox-server/Toolbox/Util/OGDF.hs
app/toolbox-server/Toolbox/Worker.hs

Module clusters are highlighted (with colored edges) when hovered and subgraph of the module cluster is shown when clicked.

Show module  dep subgraph in the selected module cluster

---

app/toolbox-server/Main.hs
app/toolbox-server/Toolbox/Render/ModuleGraph.hs
app/toolbox-server/Toolbox/Worker.hs
src/Toolbox/Util/Graph/BFS.hs
src/Toolbox/Util/Graph/Builder.hs
src/Toolbox/Util/Graph/Cluster.hs
test/Toolbox/Util/Graph/BFSSpec.hs
test/Toolbox/Util/Graph/ClusterSpec.hs

Clustered node items are limited in the range between the previous and the next large node in topological order. 
Clustering algorithm uses interleaved multi-seed staged BFS, i.e. BFS stage by stage rotating the seed (rotation order is fixed so it's greedy).

Clustering based on BFS with topological limiting

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/Render/Util.hs
plugin/src/GHCSpecter/Channel.hs
plugin/src/Plugin/GHCSpecter.hs

Recording the end time of different phases, more fine-grained timing information is retrieved and visualized. 
With this PR, Haskell compilation, assembler and linker time are separately shown in timing bar graph.

More fine-grained timing information

---

daemon/app/Main.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/Worker/ModuleGraph.hs
plugin/src/Plugin/GHCSpecter.hs

Previously, client-to-server (GHC-to-daemon) connection was made every time a message was sent.
Now, by storing session connection in the session variable, the connection is only made once and messages are queued and sent. This stabilizes the connection and enables bidirectional communication.

Session-wide connection

---

plugin/src/GHCSpecter/Comm.hs
plugin/src/Plugin/GHCSpecter.hs

when message size is an exact multiple of 1024, the last payload message is zero-sized, which caused vanishing resource error.
This fixed the bug.

Bug fix in socket communication

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/UI/ConcurReplica/DOM.hs
daemon/src/GHCSpecter/UI/ConcurReplica/Run.hs
daemon/src/GHCSpecter/UI/ConcurReplica/SVG.hs
daemon/src/GHCSpecter/UI/ConcurReplica/Types.hs
daemon/src/GHCSpecter/UI/ConcurReplica/WaiHandler.hs
daemon/src/GHCSpecter/UI/Types.hs

As the UI framework is diverted from the original concur-replica (in terms of HTML/IHTML), I internalize DOM and SVG modules in the ghc-specter code base. The IHTML data type is simplified as well.

Internalize DOM and SVG

---

daemon/app/Main.hs
daemon/package.yaml
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Control/Runner.hs
daemon/src/GHCSpecter/Control/Types.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/ConcurReplica/WaiHandler.hs
daemon/src/GHCSpecter/UI/Constants.hs
daemon/src/GHCSpecter/UI/Types/Event.hs

UI rendering is strictly confined to HTML widget building and event handling and program state change is done in a separated Control monad which is a type synonym of Free over allowed effect pattern functor. 
This allows for clean and more pure implementation of dynamic program state change as business logic part is almost pure state changing automata with event receiving coroutine operation.

Control eDSL for separation of business logic and UI rendering

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Control/Runner.hs
daemon/src/GHCSpecter/Control/Types.hs
daemon/src/GHCSpecter/Data/Assets.hs
daemon/src/GHCSpecter/Driver.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/Data/Assets.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs

Now Control and its runner is completely separated from UI monad (Widget IHTML), which guarantees the separation of state changing control process and UI rendering.
In that vein, message channel update and forcing UI refresh signal (previously called UITick, and now renamed to RefreshUI) are now separated out from Widget monad.

Separate out Control from Widget completely

---

daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/UI/ConcurReplica/DOM/Events.hs
daemon/src/GHCSpecter/UI/Constants.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs

Now scrolling events  on the timing graph panel are handled directly by control routine.

Scrolling on Timing Graph directly by custom mouse dragging control loop 

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/ConcurReplica/Run.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/Util/SourceTree.hs
daemon/src/GHCSpecter/Worker/ModuleGraph.hs

For user's convenience and for a better performance, the module tree is used as the TOC and only the selected sub-tree is expanded. The SourceView is also organized as horizontal dual pane.
For nested list indentation, setting a style text globally is needed, so I introduced runDefaultWithStyle function.

Show module tree structure in SourceView and paned view

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Render/Components/TextView.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/UI/ConcurReplica/DOM.hs
daemon/src/GHCSpecter/Util/SourceText.hs
daemon/src/GHCSpecter/Worker/CallGraph.hs
daemon/src/GHCSpecter/Worker/Hie.hs

By identifying top-level declarations and references in each top-level declaration, the call graph is constructed in a given module. For the sake of usability, the call graph is restricted in a self-package, so that users can see how function-level dependencies are set in the current GHC session.

Call Graph data extraction from a single module

---

daemon/src/GHCSpecter/GraphLayout/Algorithm/BFS.hs
daemon/src/GHCSpecter/GraphLayout/Algorithm/Builder.hs
daemon/src/GHCSpecter/GraphLayout/Algorithm/Cluster.hs
daemon/src/GHCSpecter/GraphLayout/OGDF.hs
daemon/src/GHCSpecter/GraphLayout/Types.hs
daemon/src/GHCSpecter/Render/Components/TextView.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Util/OGDF.hs
daemon/src/GHCSpecter/Worker/ModuleGraph.hs

Change the prefix Util to GraphLayout to be specific for those modules. GraphLayout.Types are also separated out.

GraphLayout module reorganization 

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Worker/Hie.hs
flake.lock

Massive calls to C++ graph layouter caused unresponsive Ctrl+C. It's unclear what exactly causes this issue. As a workaround, this PR introduces arranging the jobs serially (which is desirable after all as we want to minimize interference with GHC compilation performance) and giving a little time room (50 ms) between jobs.

Serial work queue. Ctrl-C workaround

---

daemon/app/Main.hs
daemon/package.yaml
daemon/src/GHCSpecter/Driver.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Driver/Session.hs
daemon/src/GHCSpecter/Driver/Session/Types.hs
daemon/src/GHCSpecter/Driver/Worker.hs

Top-level driver functions are moved from app/Main.hs to GHCSpecter.Driver.*.
ServerState and signal channel are packaged into a session type.

Driver module reorg and server session type

---

daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/Components/GraphView.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Util/Map.hs
daemon/src/GHCSpecter/Util/Timing.hs
plugin/src/GHCSpecter/Channel/Common/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs

Previously, ModuleName is used as a key for inspecting on each module unit compilation. Unfortunately, the ModuleName info was not available at the start time of module compilation (this is the limitation of driverPlugin, though. GHC compileOne function invocation already has module summary info when initializing the plugin for the compilation unit), so the previous method was ad hoc to keep the module start time information until the module name info is available and send together. 
Now, DriverId is assigned for each instance of driver, and send start time right at the start time and then later module name information is separately sent. This simplifies the internal logic and enable inspection before the module name arrives.

Introducing DriverId

---

daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/Session.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Types.hs
plugin/src/Plugin/GHCSpecter/Util.hs

Module name is retrieved in a more reliable and simplified way using parsedResultAction plugin.

Retrieve module name from parsedResultAction plugin

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Util/Timing.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Util.hs

When the GHC session is paused, the plugin sends back the info where each paused module compilation is at.
New breakpoint positions were also introduced, such as typecheck, pre-runPhase, post-runPhase etc.

Multiple breakpoints and send back the info where the module compilations are paused

---

daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Control/Runner.hs
daemon/src/GHCSpecter/Control/Types.hs
daemon/src/GHCSpecter/Driver.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Driver/Session/Types.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs
plugin/src/GHCSpecter/Channel/Inbound/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Types.hs

This PR introduces web console interface that enables on-demand inspection into a paused GHC session.
Made a simple message ping-pong test for the sake of test.

Console interface for inspecting a paused GHC session

---

daemon/src/GHCSpecter/Control.hs
plugin/src/GHCSpecter/Channel/Inbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Types.hs

By typing `:next`, the paused GHC session can be proceeded to the next break point for a given driver (i.e. module).

Console command for proceed to next breakpoint (:next)

---

daemon/src/GHCSpecter/Control.hs
plugin/src/GHCSpecter/Channel/Inbound/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Comm.hs
plugin/src/Plugin/GHCSpecter/Console.hs
plugin/src/Plugin/GHCSpecter/Task/UnqualifiedImports.hs
plugin/src/Plugin/GHCSpecter/Types.hs

On the console from a paused session, depending on the phase the session stop at, users can now run inspection commands allowed on the breakpoint.
As an example, the task fetching unqualified imported symbols is now allowed at Typecheck breakpoint (with the `:unqualified` command).

Interactive phase-specific command from the console

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/GraphView.hs
daemon/src/GHCSpecter/Render/Components/TextView.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/Render/Util.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs

"Sticky" checkbox is replaced by "To Current Time" button (i.e. not staying stick to the current time, but move to the current time viewport window as the button is pressed)
Console tabs now show module names. 
I made a few more minor style adjustments.

Further style adjustment

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
plugin/src/GHCSpecter/Channel/Inbound/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Console.hs
plugin/src/Plugin/GHCSpecter/Task/PrintCore.hs

Introduced new CorePlugin that inserts breakpoints before and after every core-to-core transformation.
At the breakpoint, users can inspect the current Core expression of the module under the inspection from the console.

Breakpoint at Core2Core transformation

---

daemon/src/GHCSpecter/Render/Components/Console.hs
plugin/src/Plugin/GHCSpecter.hs

Console is scrolled down to the end of a new content. 
Unfortunately, this cannot be easily done via concur-replica as it does not support property update via VDOM.
So the solution is rather hacky using direct <script> insertion into the console element. We will revisit this when a proper solution by modifying concur-replica is implemented.

Automatic scroll-down console when new entry comes

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Server/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Console.hs
plugin/src/Plugin/GHCSpecter/Task/PrintCore.hs
plugin/src/Plugin/GHCSpecter/Task/UnqualifiedImports.hs

For semantic formatting on the web frontend side, Core data is converted to Tree using Data.Data, serialized and sent. Console shows the tree in drawForest format.

Send structural Core data, not pretty-printed text

---

plugin/src/Plugin/GHCSpecter/Task/PrintCore.hs
plugin/src/Plugin/GHCSpecter/Task/UnqualifiedImports.hs

`gfoldl` iterates over arguments, not including the constructor itself. Constructor should be handled at the top level before applying `gfoldl`.

Bug fix in core2tree

---

daemon/src/GHCSpecter/Data/GHC/Core.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/GHCCore.hs
plugin/src/Plugin/GHCSpecter/Task/PrintCore.hs

Left-leaning binary tree of App application is interpreted as curried application for a better visualization.
The recursive binding is also handled.
Used unique suffix for Var Id as well.

Handling curried application and recursive binding in Core visualization

---

daemon/src/GHCSpecter/Render/Components/Console.hs
ghc-specter.yaml.sample
plugin/src/GHCSpecter/Config.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Comm.hs
plugin/src/Plugin/GHCSpecter/Types.hs

By setting `start_with_breakpoint: True` in ghc-specter.yaml, the session is paused from the beginning. Useful for debugging.
Driver initialization step is split into GHC session init and Driver session init, so that the code gets simplified.

GHC session can be started as paused by config

---

daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/ConsoleItem.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter/Task/Core2Core.hs

Now clicking the resultant buttons from `:list-core` will populate console input with the corresponding `:print-core` commands.

Generate button from the result of list-core

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Data/GHC/Core.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/ConsoleItem.hs
daemon/src/GHCSpecter/Render/Components/GHCCore.hs
plugin/src/Plugin/GHCSpecter/Task/Core2Core.hs

by suppressing Type and handling LitNumber correctly. 
NOTE: Later, type suppression should be handled optionally and more consistently and matched with GHC default textual presentation as well.

Refine Core presentation

---

daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Server/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs

`:goto-source` is introduced, which automatically open source-view tab from the focused module console.

Goto-source from console

---

plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs

No need to wait for the end of compilation.
PostRunPhase has the phase information of both before-run and after-run not to be confusing.

Send HIE information as early as typecheck plugin

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/TextView.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/UI/Types.hs
plugin/src/GHCSpecter/Channel/Inbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Console.hs
plugin/src/Plugin/GHCSpecter/Task/Typecheck.hs

`:print-core (symbol)` will  automatically locate the source position if in source view mode.

Scroll to the source location when printing core

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Control/Runner.hs
daemon/src/GHCSpecter/Control/Types.hs
daemon/src/GHCSpecter/Data/Timing/Types.hs
daemon/src/GHCSpecter/Data/Timing/Util.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs
daemon/src/GHCSpecter/Worker/Timing.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs

The last compiled upper dependency blocking a given module and downstream modules that was blocked by a given module are now interactively shown.

Show blocker modules in both up/downstream direction interactively in TimingView

---

plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Console.hs

parsedResultAction, renamedResultAction, spliceRunAction can be paused.
Typecheck breakpoint is renamed to TypecheckResultAction to be more correct.

Place breakpoints at additional points using source plugins

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/Components/ConsoleItem.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs
daemon/src/GHCSpecter/Worker/CallGraph.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter/Console.hs
plugin/src/Plugin/GHCSpecter/Task/Core2Core.hs
plugin/src/Plugin/GHCSpecter/Task/Typecheck.hs

Call graph, :show-expr, :show-renamed results are now also shown in supplementary view (right pane in the source view).
The results are accumulated and can be navigated via tabs.

Tabbed Supplementary View interface

---

plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Comm.hs

Read session and overwrite on the session should be done in a single atomic STM operation. 
Unfortunately, as a consequence, the necessary IO action should be done outside beforehand, which means the action will be done multiple times per every driver start. This is due to the limited plugin point (as we cannot put a compatible plugin in the beginning of GHC session. There exists frontend plugin, but that's not compatible with cabal, which uses hard-coded `ghc --make` command yet) The IO operation is nothing but timestamping and reading config, so I put up with a little redundancy here.

Race condition in initialization correctly handled

---

daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Worker/Hie.hs
daemon/src/GHCSpecter/Worker/ModuleGraph.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Types.hs
plugin/src/Plugin/GHCSpecter/Util.hs

Previously, source files were loaded as GHC compiles the module, but there is no reason to wait as the file path information is already there when getting the module graph.

Source file load upfront in the beginning

---

daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Worker/Hie.hs
plugin/package.yaml
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Comm.hs
plugin/src/Plugin/GHCSpecter/Console.hs
plugin/src/Plugin/GHCSpecter/Hooks.hs
plugin/src/Plugin/GHCSpecter/Types.hs

ghc-specter-plugin didn't work with GHC 9.4 as it did with GHC 9.2 because the driver plugin runs only once per session with GHC 9.4 while it happpened to run per every module compilation with GHC 9.4. This basically broke all the existing state-sharing method across different plugins in a single module compilation pipeline as I used plugin closures constructed at the driver initiatialization timing. 
Now, a new state-sharing mechanism is introduced via CommandLineOption.  From GHC 9.4, the TPhase used for runPhase is more consistently defined in a type-safe manner (using GADT), and customized HscEnv can be shared in a single phase. I made a preprocess at the beginning of each runPhase to pass the shared driver id through CommandLineOption passed to each sub-phase plugin.
In this way, the …

GHC 9.4: driverId assigned to each module compilation through runPhaseHook

---

daemon/assets/ghc-specter.css
daemon/src/GHCSpecter/Data/Timing/Types.hs
daemon/src/GHCSpecter/Data/Timing/Util.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/Components/TimingView.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/UI/Constants.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/GHCSpecter/Data/GHC/Orphans.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Hooks.hs

By reading RTSStats and allocation counter, the memory allocation information in a single module compilation is collected and shown as bar graph juxtaposed with the timing view.

View memory allocation per phase in a single module compilation

---

daemon/src/GHCSpecter/Render/Session.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs

Show what mode and backend the current GHC session is operated on.
GhcMode = CompManager | OneShot | MkDepend
Backend = NCG | LLVM | ViaC | Interpreter | NoBackend

Show GHC Mode and Backend information

---

flake.lock
flake.nix

An up-to-date version (fixed for GHC 9.2 and 9.4) of ghc-debug is now integrated into devShell.

ghc-debug included in dev env

---

plugin/src/Plugin/GHCSpecter/Hooks.hs

The "driver id" was not provided in the phases other than the Hsc phase, so the breakpoints were not working (especially in Core2Core steps which is in the HscPostTc phase)
By providing replaceEnvInTPhase, HscEnv is now always updated with the driver id on GHC 9.4. (GHC 9.2 works as is since it uses different mechanism).

Bug fix: provide driverId to all the phases

---

daemon/src/GHCSpecter/Data/GHC/Core.hs
daemon/src/GHCSpecter/Render/Components/ConsoleItem.hs

A few primitive types are now represented with a module qualifier in GHC 9.4.
Bind -> GHC.Core.Bind
Literal -> GHC.Types.Literal.Literal
AltCon -> GHC.Core.AltCon
Alt -> GHC.Core.Alt
Expr -> GHC.Core.Expr
This fixes the Core viewer in ghc-specter-daemon.

Adjust qualified Core representation for GHC 9.4.

---

daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/UI/Help.hs
daemon/src/GHCSpecter/UI/Types.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Console.hs

Previously, resumed module from pause was detected by an asynchronous "killed thread" exception as the resume is made through killThread. However, this mechanism is too brittle to rely on and there are no need to notify the resume. 
Instead, the paused module list is just to be managed on the daemon side and resume button will wipe out the paused modules.

Fix incorrect paused module behavior

---

daemon/app/Main.hs
daemon/src/GHCSpecter/GraphLayout/Algorithm/Cluster.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Util/ModuleGraph.hs
daemon/src/GHCSpecter/Worker/ModuleGraph.hs
ghc-specter.yaml.sample
plugin/src/GHCSpecter/Config.hs

Project by project, this number should be different. Therefore, it is better to be configured in ghc-specter.yaml.

moduleClusterSize is configurable.

---

daemon/app/Main.hs
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Data/Timing/Util.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/UI/Types/Event.hs
daemon/src/GHCSpecter/Worker/Timing.hs
ghc-specter.yaml.sample
plugin/src/GHCSpecter/Config.hs

Introduced BlockerDetailLevel, which dynamically filters out blocker modules by a given number of blocked modules. 
Four levels (>=2, >=3, >=4, >=5) can be selected via radio buttons.

User can dynamically see blocker graph with different blocker level 

---

.github/workflows/build.yml
daemon/src/GHCSpecter/Data/GHC/Core.hs
daemon/src/GHCSpecter/UI/ConcurReplica/WaiHandler.hs
daemon/src/GHCSpecter/Worker/Hie.hs
daemon/test/GHCSpecter/GraphLayout/Algorithm/ClusterSpec.hs
flake.lock
flake.nix
plugin/src/Plugin/GHCSpecter.hs

This PR introduces Github action CI for ghc-specter project with nix-based build targets.
I also cleaned up dependencies, using hackage versions for them as far as we can.

Install CI and clean up dependencies

---

.github/workflows/docs.yml
docs/Makefile
docs/conf.py
docs/getting_started.md
docs/index.rst
docs/make.bat
flake.nix

Through CI, the generated documentation will be shown on https://https://mercurytechnologies.github.io/ghc-specter
The document generation is only on push master.

Install read-the-docs style documentation page

---

daemon/package.yaml
daemon/src/GHCSpecter/Worker/Hie.hs
flake.lock
flake.nix
nix/ghcHEAD/ghcHEAD-cabal.project
nix/ghcHEAD/shell.nix
plugin/package.yaml
plugin/src/GHCSpecter/Util/GHC.hs
plugin/src/Plugin/GHCSpecter.hs
plugin/src/Plugin/GHCSpecter/Hooks.hs
plugin/src/Plugin/GHCSpecter/Tasks.hs
plugin/src/Plugin/GHCSpecter/Tasks/Core2Core.hs
plugin/src/Plugin/GHCSpecter/Tasks/Typecheck.hs

based on the ghc.nix shell and head.hackage, locally built GHC can be used for building ghc-specter packages.
Nix provides haskell env only for building GHC (based on ghc 9.2.4) and C++ deps for ghc-specter, but the Haskell deps for ghc-specter are compiled via cabal.project specification.
Note that this shell is for testing this project with up-to-date GHC, and not intended for reproducible packaging.

ghcHEAD shell

---

daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Render/ModuleGraph.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Render/Timing.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Worker/Timing.hs
nix/ghcHEAD/ghcHEAD-cabal.project
nix/ghcHEAD/shell.nix
plugin/ghc-specter-plugin.cabal
plugin/src-ghc92/Plugin/GHCSpecter.hs
plugin/src-ghc92/Plugin/GHCSpecter/Init.hs
plugin/src-ghc94/Plugin/GHCSpecter.hs
plugin/src-ghc94/Plugin/GHCSpecter/Hooks.hs
plugin/src-ghc94/Plugin/GHCSpecter/Init.hs
plugin/src-ghc96/Plugin/GHCSpecter.hs
plugin/src-ghc96/Plugin/GHCSpecter/Hooks.hs
plugin/src-ghc96/Plugin/GHCSpecter/Init.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/Plugin/GHCSpecter/Comm.hs
plugin/src/Plugin/GHCSpecter/Types.hs

Since GHC 9.6, the driver plugin is initialized before analyzing ModuleGraph (see [1]), and therefore, in the previous implementation, ghc-specter could not get the module graph information correctly. 
Now, I split ModuleGraphInfo out from SessionInfo so that the module graph information can be sent later when available (currently, the earliest time one can get is when Hsc phase started for the first module afaict).
Subsequent changes for GHC 9.4 and 9.6. Tested with Agda repo.
[1] https://github.com/ghc/ghc/blob/ghc-9.6.1-release/compiler/GHC/Driver/Make.hs#L668

Fix module graph on ghc 9.6

---

daemon-exp/app/ghc-specter-daemon-exp/Main.hs
daemon-exp/ghc-specter-daemon-exp.cabal
nix/ghcHEAD/ghcHEAD-cabal.project

Using the shared communication module as daemon, the module graph is drawn natively. The web interface suffered from performance issues in the current design (and bad dependency issue with up-to-date GHC), this is the way to go with minimal deps. Fortunately, the gi-* packages have quite small dep footprint.

Native module graph rendering

---

daemon-exp/app/ghc-specter-daemon-exp/Handler.hs
daemon-exp/app/ghc-specter-daemon-exp/Main.hs
daemon-exp/app/ghc-specter-daemon-exp/ModuleGraph.hs
daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs
daemon-exp/app/ghc-specter-daemon-exp/Timing.hs
daemon-exp/app/ghc-specter-daemon-exp/Types.hs
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Control/Runner.hs
daemon/src/GHCSpecter/Control/Types.hs
daemon/src/GHCSpecter/Driver.hs
daemon/src/GHCSpecter/Driver/Session.hs
daemon/src/GHCSpecter/UI/Types.hs

The monolithic goCommon event handling is distributed over the corresponding event handlers per each branch.
Runner environment is now gathered up into a single data type RunnerEnv.
Also supports active refreshing for the case of gtk redrawing.

Refactoring Control.Runner and control branches 

---

daemon-exp/app/ghc-specter-daemon-exp/ModuleGraph.hs
daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs
daemon-exp/app/ghc-specter-daemon-exp/Timing.hs
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render/Components/GraphView.hs
daemon/src/GHCSpecter/Render/Components/TimingView.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/Util/Transformation.hs
render/src/GHCSpecter/Graphics/DSL.hs

By introducing Scene with local and global view port information, the corresponding coordinate transformations needed for event to hit items are done properly.

Proper subcomponent event coordinate transformation

---

daemon-exp/app/ghc-specter-daemon-exp/Main.hs
daemon-exp/app/ghc-specter-daemon-exp/Render/Common.hs
daemon-exp/app/ghc-specter-daemon-exp/Render/ModuleGraph.hs
daemon-exp/app/ghc-specter-daemon-exp/Render/Session.hs
daemon-exp/app/ghc-specter-daemon-exp/Render/SourceView.hs
daemon-exp/app/ghc-specter-daemon-exp/Render/Timing.hs
daemon-exp/app/ghc-specter-daemon-exp/Renderer.hs
daemon-exp/app/ghc-specter-daemon-exp/Types.hs
daemon-exp/ghc-specter-daemon-exp.cabal
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Render/Components/GraphView.hs
daemon/src/GHCSpecter/Render/Components/ModuleTree.hs
daemon/src/GHCSpecter/Render/Components/Tab.hs
daemon/src/GHCSpecter/Render/Components/TextView.hs
daemon/src/GHCSpecter/Render/Components/TimingView.hs
daemon/src/GHCSpecter/Render/ConcurReplicaSVG.hs
daemon/src/GHCSpecter/Render/Session.hs
daemon/src/GHCSpecter/Render/SourceView.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/Util/Transformation.hs
render/src/GHCSpecter/Graphics/DSL.hs

For high-level component rendering, hide low-level Render by wrapping  it into ReaderT.
Low-level events are also wrapped into HitEvent, which is polymorphic for the future use.

Wrap Render monad and low-level event

---

daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/TimingView.hs
daemon/src/GHCSpecter/Render/Components/Util.hs

Also used NonEmpty for item layout safely (no partial `maximum`)

Console button items

---

daemon-exp/app/ghc-specter-daemon-exp/Render/Parts/Timing.hs
daemon/src/GHCSpecter/Render/Components/Console.hs
daemon/src/GHCSpecter/Render/Components/TimingView.hs
daemon/src/GHCSpecter/Render/Components/Util.hs

the element layout algorithm didn't distinguish grouped items from single primitive items
so items after button groups were not correctly displayed. Now it's fixed.

Positioning grouped console items correctly

---

logcat/util/Extract.hs
logcat/util/Main.hs
logcat/util/flake.lock
logcat/util/flake.nix

Html generated by eventlog2html by large eventlog data with info table is
corrupted due to stack overflow in javascript. This adds a simple utility
to display the content. Used for profiling GHC.

eventlog2html subclone to handle large eventlog data 

---

logcat/util/FromHTML.hs
logcat/util/GHCEvents.hs
logcat/util/Main.hs
logcat/util/Types.hs
logcat/util/flake.nix

now we do not have to rely on generated html file from eventlog2html. 
a step towards live info-table profiling.

Handle eventlog directly to get closure statistics

---

daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Driver/Terminal.hs
daemon/src/GHCSpecter/UI/Types/Event.hs
daemon/src/GHCSpecter/Util/Dump.hs

module graph information can be dumped from the console like timing and memory allocation info.

Dump cluster module graph from console

---

daemon/src/GHCSpecter/Driver.hs
daemon/src/GHCSpecter/Driver/Comm.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/Worker/ModuleGraph.hs
plugin/src-ghc96/Plugin/GHCSpecter/Init.hs
plugin/src/GHCSpecter/Channel/Outbound/Types.hs
plugin/src/GHCSpecter/Config.hs

users do not need to give the cluster size value.

Automatically computed cluster node size by heuristic

---

daemon/app/ghc-specter-daemon/Render.hs
daemon/app/ghc-specter-daemon/Render/Console.hs
daemon/app/ghc-specter-daemon/Util/GUI.hs
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/UI/Types.hs
flake.lock
plugin/src/GHCSpecter/Config.hs

`:goto-source` console command now goes to the source tab.
and session pause/resume works regardless of the selected tab (bug happened as the button is out of session tab).

Tab-related bug fixes

---

daemon/app/ghc-specter-daemon/Main.hs
daemon/app/ghc-specter-daemon/Render.hs
daemon/app/ghc-specter-daemon/Render/Console.hs
daemon/app/ghc-specter-daemon/Render/Session.hs
daemon/app/ghc-specter-daemon/Util/GUI.hs
daemon/app/ghc-specter-daemon/Util/Render.hs
daemon/ghc-specter-daemon.cabal
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Control/DSL.hs
daemon/src/GHCSpecter/Control/Runner.hs
daemon/src/GHCSpecter/Control/Types.hs
daemon/src/GHCSpecter/UI/Console.hs
daemon/src/GHCSpecter/UI/Session.hs
flake.lock

and Session and compilation status as well.
Custom rendering is now restricted to ghc-specter-oriented components.

Console uses native widgets

---

daemon/app/ghc-specter-daemon-terminal/Main.hs
flake.lock
flake.nix
render/ghc-specter-render.cabal

hs-ogdf was the culprit responsible for redundant deps.
Also use `shellFor` for dev env to tidy up nix expr.

Dependency clean-up and better dev/env shell nix expr

---

plugin/src-ghc96/Plugin/GHCSpecter/Hooks.hs

GHC should be paused after sending the current status info in runPhaseHook. This solves the annoying "no module name" problem at the beginning of Hsc phase.

Fix breakpoint position in runPhaseHook

---

daemon/ghc-specter-daemon.cabal
daemon/src/GHCSpecter/Control.hs
daemon/src/GHCSpecter/Data/GHC/Hie.hs
daemon/src/GHCSpecter/Data/Timing/Types.hs
daemon/src/GHCSpecter/Data/Timing/Util.hs
daemon/src/GHCSpecter/Driver/Session/Types.hs
daemon/src/GHCSpecter/Layouter/Graph/Types.hs
daemon/src/GHCSpecter/Server/Types.hs
daemon/src/GHCSpecter/UI/Constants.hs
daemon/src/GHCSpecter/UI/Types.hs
daemon/src/GHCSpecter/Worker/CallGraph.hs

from now on, we only use GHC-provided record syntax or internal version of lens.

Remove lens dependency.

---

cabal.project
flake.lock
flake.nix

for non-NixOS linux, one need to invoke an app using OpenGL with `nixGL`.
```
$ nix develop --impure
$ nixGL cabal run ghc-specter-daemon:exe:ghc-specter-daemon
```

Integrate nixGL for non-NixOS linux

---

daemon/app/ghc-specter-daemon/Util/GUI.hs
daemon/app/ghc-specter-daemon/Util/Plot.hs
daemon/ghc-specter-daemon.cabal

The implot utility function is not used yet. So disabled it for now (the transitive dep implot -> imgui caused unnecessary build issues which needs patches on nix expr.)

Disable unused implot for now 
